#!/usr/bin/python

import argparse
import os

parser = argparse.ArgumentParser()
parser.add_argument('command')
parser.add_argument('-p', '--prefix', help='prefix', required=True)
parser.add_argument('-s', '--static', help='build statically', action='store_true')
args = parser.parse_args()

def command(c):
    print c
    os.system(c)

if args.command == 'build':
    cmd = './waf configure --prefix=%s' % args.prefix
    if args.static:
        cmd += ' --static-libdcp --static-openjpeg'
    cmd += ' build install'
    command(cmd)
