def build(bld):
    obj = bld(features = 'cxx cxxprogram')
    obj.name   = 'examples'
    obj.use    = 'libdcp'
    obj.uselib = 'OPENJPEG CXML'
    obj.source = 'make_dcp.cc'
    obj.target = 'make_dcp'
    obj.install_path = ''
