#!/bin/bash

export LD_LIBRARY_PATH=build/src:build/asdcplib/src:$LD_LIBRARY_PATH
if [ "$1" == "--debug" ]; then
    shift
    gdb --args build/tools/dcpdecryptmxf "$@"
elif [ "$1" == "--valgrind" ]; then
    shift
    valgrind --tool="memcheck" --leak-check=full --show-reachable=yes build/tools/dcpdecryptmxf "$@"
else
    build/tools/dcpdecryptmxf "$@"
fi
