#!/bin/bash

export LD_LIBRARY_PATH=build/src
if [ "$1" == "--debug" ]; then
    shift
    gdb --args build/examples/read_dcp "$@"
elif [ "$1" == "--valgrind" ]; then
    shift
    valgrind --tool="memcheck" --leak-check=full --show-reachable=yes build/examples/read_dcp "$@"
else
    build/examples/read_dcp "$@"
fi
