#!/bin/bash

# Private test data; this is stuff that is non-distributable
private=../libdcp1-test-private

export LD_LIBRARY_PATH=build/src:build/asdcplib/src:$LD_LIBRARY_PATH
if [ "$1" == "--debug" ]; then
    shift
    gdb --args build/test/bench $private
elif [ "$1" == "--valgrind" ]; then
    shift
    valgrind --tool="memcheck" build/test/bench $private
elif [ "$1" == "--callgrind" ]; then
    shift
    valgrind --tool="callgrind" build/test/bench $private
else
    build/test/bench $private
fi
