def build(bld):
    obj = bld(features = 'cxx cxxprogram')
    obj.use = ['libdcp']
    obj.source = 'dcpdiff.cc'
    obj.target = 'dcpdiff'

    obj = bld(features = 'cxx cxxprogram')
    obj.use = ['libdcp']
    obj.source = 'dcpinfo.cc'
    obj.target = 'dcpinfo'

