def build(bld):
    obj = bld(features = 'cxx cxxprogram')
    obj.use = ['libdcp%s' % bld.env.API_VERSION]
    obj.uselib = 'OPENJPEG CXML'
    obj.source = 'dcpdiff.cc common.cc'
    obj.target = 'dcpdiff'

    obj = bld(features = 'cxx cxxprogram')
    obj.use = ['libdcp%s' % bld.env.API_VERSION]
    obj.uselib = 'OPENJPEG CXML'
    obj.source = 'dcpinfo.cc common.cc'
    obj.target = 'dcpinfo'

    obj = bld(features = 'cxx cxxprogram')
    obj.use = ['libdcp%s' % bld.env.API_VERSION]
    obj.uselib = 'OPENJPEG CXML'
    obj.source = 'dcpdumpsub.cc'
    obj.target = 'dcpdumpsub'

