def build(bld):
    obj = bld(features = 'cxx cxxshlib')
    obj.name = 'libdcp'
    obj.target = 'dcp'
    obj.export_includes = ['.']
    obj.uselib = 'BOOST_FILESYSTEM OPENSSL SIGC++ LIBXML++ OPENJPEG'
    obj.use = 'libkumu-libdcp libasdcp-libdcp'
    obj.source = """
                 asset.cc
                 asset_map.cc
                 cpl.cc
                 dcp.cc        
                 dcp_time.cc
                 mxf_asset.cc
                 sound_asset.cc
                 subtitle_asset.cc
                 picture_asset.cc
                 picture_frame.cc
                 pkl.cc
                 util.cc
                 metadata.cc
                 version.cc
                 test_mode.cc
                 types.cc
                 xml.cc
                 sound_frame.cc
                 """

    headers = """
              dcp.h
              metadata.h
              types.h
              exceptions.h
              test_mode.h
              version.h
              picture_asset.h
              sound_asset.h
              subtitle_asset.h
              asset.h
              picture_frame.h
              sound_frame.h
              """

    bld.install_files('${PREFIX}/include/libdcp', headers)
